### ISSUE TITLE
IOS 17 compatibility?

### ISSUE THREAD

**Issue by shiprec** [dakhnod/FakeTag#10]
I was wondering if your FakeTag still works even with IOS 17 devices.  We are running into issues with getting reports from any device that upgraded to IOS 17...

Thank you in advance for any insights you might have!

**Comment by dakhnod** [comment]
oh, that would be rather unfortunate. Wonder how they did that, in case it was intentional...

In any case, no idea, sorry

**Comment by shiprec** [comment]
Appreciate the response!
