### ISSUE TITLE
Absent custom includes directory

### ISSUE THREAD

**Issue by lspeltie** [dakhnod/FakeTag#3]
There's a reference to a custom includes directory in the makefile.

    $(CUSTOM_INCLUDES_DIR)/battery_service/battery.c \
    $(CUSTOM_INCLUDES_DIR)/boards/boards.c \

Where do I find these files, and if they're not public, would you mind providing the files you used for your specific board?

**Comment by dakhnod** [comment]
I've pushed the files and updated the Makefile, does it work for you now?

**Comment by lspeltie** [comment]
> I've pushed the files and updated the Makefile, does it work for you now?

Yes, I have gotten it compiled now. Thanks.
